### ISSUE TITLE
Numbered wrong when migrating from jupyter-book to Sphinx

### ISSUE THREAD

**Issue by luweizheng** [executablebooks/sphinx-external-toc#108]
### Describe the bug

**context**
I have built a site with jupyter-book successfully. Now I want to use the features of `sphinx-book-theme` so I migrate from jupyter-book to sphinx.

I use the generated `conf.py` with  

```
extensions = ['sphinx_external_toc',]
external_toc_exclude_missing = True
external_toc_path = '_toc.yml'
```

and my `_toc.yml` remains the same like:

```
format: jb-book
root: index
parts:
  - caption: 引言
    numbered: true
    chapters:
    - file: ch-intro/index
      sections:
        - file: ch-intro/computer-architecture
        - file: ch-intro/thread-process
  
  - caption: Dask
    numbered: true
    chapters:
    - file: ch-dask/index
      sections:
        - file: ch-dask/dask-intro
```

But it turns out that it cannot continue numbers between different chapters.

![image](https://github.com/executablebooks/sphinx-external-toc/assets/57242864/669975e2-1fcb-4822-8836-966da526abdb)

### Reproduce the bug

What do I need to do to fix this issue?

### List your environment

sphinx_external_toc           0.3.1
sphinx-multitoc-numbering     0.1.3

**Comment by luweizheng** [comment]
I use a workaround to fix this issue:

```
root: index
subtrees:
- numbered: true
  entries:
  - file: ch-intro/index
    entries:
    - file: ch-intro/computer-architecture
    - file: ch-intro/thread-process
  - file: ch-dask/index
    entries:
    - file: ch-dask/dask-intro
```

The UI is slightly different now:

![image](https://github.com/executablebooks/sphinx-external-toc/assets/57242864/a55a46f4-df80-40de-8e57-499f513b6f0b)
