### ISSUE TITLE
Global options key in `_toc.yml` not reflected in `external_site_map` json representation 

### ISSUE THREAD

**Issue by AakashGfude** [executablebooks/sphinx-external-toc#38]
On reading the JSON representation of the `external_site_map` using:
```
site_map = app.config.external_site_map
json_rep = yaml.dump(site_map.as_json())
```
it was found that it does not have the information of global `options` key stored in it.

Example:

with the following toc representation:

```
format: jb-book
root: content/preface
options:
 numbered: True
chapters:
- file: content/ch1
  options:
   numbered: True
- file: content/ch2
  sections:
    - file: content/ch4
    - file: content/ch5
```
 
the corresponding JSON representation of `external_site_map` object was :

```
documents:
  content/ch1:
    docname: content/ch1
    subtrees: []
    title: null
  content/ch2:
    docname: content/ch2
    subtrees:
    - caption: null
      hidden: true
      items:
      - content/ch4
      - content/ch5
      maxdepth: -1
      numbered: false
      reversed: false
      titlesonly: true
    title: null
  content/ch4:
    docname: content/ch4
    subtrees: []
    title: null
  content/ch5:
    docname: content/ch5
    subtrees: []
    title: null
  content/preface:
    docname: content/preface
    subtrees:
    - caption: null
      hidden: true
      items:
      - content/ch1
      - content/ch2
      maxdepth: -1
      numbered: true
      reversed: false
      titlesonly: true
    title: null
file_format: jb-book
meta: {}
root: content/preface
```

As can be seen, the local options are being passed through, but the global one is not. Perhaps it should have been in `meta` key?

cc: @mmcky

**Comment by mmcky** [comment]
@AakashGfude just checking re: `sphinx internals`. It looks like to top level toctree:

```
  content/preface:
    docname: content/preface
    subtrees:
    - caption: null
      hidden: true
      items:
      - content/ch1
      - content/ch2
      maxdepth: -1
      numbered: true
      reversed: false
      titlesonly: true
    title: null
```

does have `numbered: true` -- is it possible that `sphinx` inherits this down the line during a `transform` phase?
