### ISSUE TITLE
Section Headings

### ISSUE THREAD

**Issue by lornajane** [executablebooks/sphinx-external-toc#43]
**Is your feature request related to a problem? Please describe.**

I would love to be able to add plain text labels or section headings into my navigation. Right now I have "pointless" pages that just make the navigation folding for another section work. I'd appreciate a plain text option, for example we have a subsection "concepts" that holds too much stuff to have open by default but I have to have a "concepts" page that performs no actual purpose, it's just to make the navigation work.

**Describe the solution you'd like**

Have an option to have a plain text entry instead of a link. If it has children, it's collapsible. So like an entry that only has the title field to display, but doesn't link anywhere.

**Describe alternatives you've considered**

Going back to maintaining all those toctree entrires in all my files to get the section heading feature. Doing what I have now with a page that just displays the tables of contents or some sort of introduction to a navigation section.

If there are more alternatives, I'm happy to hear about possible workarounds

**Comment by chrisjsewell** [comment]
Thanks!
To note, this came out of a discussion on Slack, so I understand the use case here and agree it would be a nice addition

**Comment by trulede** [comment]
I've encountered a similar thing:

```
---
root: intro.md
defaults:
  titlesonly: True
subtrees:
  - caption: Schemas
    titlesonly: False
    entries:
      - file: schemas/flatbuffers/__index__.md   <<<< This file does nothing, just wanted a grouping in the TOC
        subtrees:
          - entries:
              - glob: schemas/flatbuffers/*``    <<<< Content is here
```

Before I read the manual, I did think this might work:
```
---
root: intro.md
defaults:
  titlesonly: True
subtrees:
  - caption: Schemas
    titlesonly: False
    entries:
      - caption: Flatbuffers
        subtrees:
          - entries:
              - glob: schemas/flatbuffers/*
```
