### ISSUE TITLE
Allow `part` to be a page loaded from a file

### ISSUE THREAD

**Issue by So-Cool** [executablebooks/sphinx-external-toc#58]
### Description / Summary

Load part content from a file via the following ToC syntax
```yml
format: jb-book
root: index
parts:
  - file: part_1/index
    chapters:
      - file: part_1/chapter_1
      - file: part_1/chapter_2/index
        sections:
          - file: part_1/chapter_2/section_1
          - file: part_1/chapter_2/section_2
```

### Value / benefit

- Allows to write individual preface for each part -- this page won't be numbered as opposed to individual chapters
- Makes the parts--chapters ToC syntax consistent with chapters--sections syntax

### Implementation details

- The `file` key seems to be accepted for `parts` entries, but it has no effect on the ToC

**Comment by chrisjsewell** [comment]
Heya, unless I'm mistaken, this is not possible within the sphinx toctree framework:

A part equates to a single toctree in a file with a caption:

```
.. toctree::
   :caption: This is the part title

   chapter1
   chapter2
```

I don't see how you could make this fit with adding a part prefix, unless there were upstream changes to sphinx's toctree directive.
Not to say that I wouldn't welcome it, but I don't see how it can currently be achieved in a "trivial" manner

**Comment by So-Cool** [comment]
I thought it would be a matter of a simple tweak given that it worked in jupyter-book 0.10.1 (see [source](https://github.com/simply-logical/simply-logical/blob/pf-release/_toc.yml) and [book](https://too.simply-logical.space/src/simply-logical.html)). Do you know what has changed with the migration to the new ToC syntax that broke this functionality?

**Comment by chrisjsewell** [comment]
Are you sure you shouldn't be using the jb-article format, which essentially start a level down, and would allow you to achieve this. This is probably how it was working previously

**Comment by So-Cool** [comment]
I've had 3 levels of nesting
```yml
- part: Part 1
  file: src/text/1_part_i/_part_i.md
  chapters:
  - file: src/text/1_part_i/1.0.md
    sections:
      - file: src/text/1_part_i/1.1.md
```
The jb-article documentation is quite sparse but I don't think it allows for complex nesting.

However, your comment put me on the right track to find a solution. By using the raw ToC syntax I can get the result that I want
```yml
root: index
entries:
  - file: part_1/index
    options:
      numbered: true
    entries:
      - file: part_1/chapter_1
      - file: part_1/chapter_2/index
        entries:
          - file: part_1/chapter_2/section_1
```

Maybe it's worth discussing the raw ToC syntax in the Jupyter Book documentation in case people are looking for non-standard ToC structures. What do you think?
