### ISSUE TITLE
tableofcontents maxdepth directive not applied

### ISSUE THREAD

**Issue by ZviBaratz** [executablebooks/sphinx-external-toc#59]
### Describe the problem

The table of contents rendered by the `tableofcontents` directive shows only one level, even when the `maxdepth` parameter in the book's `_toc.yml` is set to some higher number. 

### Link to your repository or website

https://zvibaratz.github.io/phd/content.html

### Steps to reproduce

1. Create a book with some "deep" headers and a `_toc.yml` such as:
```yml
format: jb-book
root: front
chapters:
- file: abstract
- file: content
  options:
    numbered: true
    maxdepth: 4
  sections:
  - file: lists
  - file: chapters/introduction
  ...
```

### The version of Python you're using

3.9.9

### Your operating system

Linux (Kubuntu)

### Versions of your packages

```
Jupyter Book      : 0.12.1
External ToC      : 0.2.3
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.1
Sphinx Book Theme : 0.1.7
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.9
```

### Additional context

The issue is opened following the discussion in executablebooks/meta#592.
