### ISSUE TITLE
`options.numbered: true` does not work when using parts

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-external-toc#72]
### Describe the bug

When you:

- Have a TOC that defines multiple parts
- Use a top-level option configuration that turns on numbering:
  ```yaml
  ...
  options:
    numbered: true
  ...
  ```

Then the resulting documentation doesn't actually have any numbering. This only happens with **parts**, it works fine when the TOC just defines chapters.

ref: https://github.com/executablebooks/jupyter-book/issues/1628

### Reproduce the bug

Here are two TOCs that produced the error, then fixed it:

No numbering happens:

```yaml
format: jb-book
options:
  numbered: true
root: intro
parts:
  - caption: Part 1
    chapters:
      - file: file1
  - caption: Part 2
    chapters:
      - file: file2
```

It can be fixed by manually specifying the `numbered: true` option on each part:

```yaml
format: jb-book 
root: intro
parts:
  - caption: Part 1
    numbered: true
    chapters:
      - file: file1
  - caption: Part 2
    numbered: true
    chapters:
      - file: file2
```

### List your environment

Here's the environment listed in the referenced issue:

```
Jupyter Book      : 0.12.1
External ToC      : 0.2.3
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.1
Sphinx Book Theme : 0.1.10
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.10
```
