### ISSUE TITLE
HTML build fails when subtree starts with subtree

### ISSUE THREAD

**Issue by n8willis** [executablebooks/sphinx-external-toc#89]
### Describe the bug

**context**
When the first entry in a subtree is another subtree, the `make html` build fails, with etoc complaining that the entry is not a file, glob, or url.

For example:
```
root: README
options:
  maxdepth: 2
subtrees:
- maxdepth: 1
  entries:
  - file: index
    title: Overview
- maxdepth: 2
  caption: Script shaping
  entries:
  - subtrees:
    - numbered: 3
      maxdepth: 2
      caption: Indic
      entries:
      - file: opentype-shaping-indic-general
        title: General model
```

(that's real-world start-of-external-TOC from [this project,](https://github.com/n8willis/opentype-shaping-documents/tree/sphinx-markup) if anyone's curious.)

**expectation**
I expected the TOC to be built as defined.

There's certainly no reason that subtrees can't be nested within other subtrees. In fact, the extension docs show that. This bug is just (or appears to be just) when a subtree is the first item in the `entries`. Notably, 

**bug**
```
Extension error:
[etoc] entry does not contain one of {'glob', 'file', 'url'} @ '/subtrees/1/entries/0'
make: *** [Makefile:20: html] Error 2
```

If I'm reading the single-quoted output part there correctly, it's crashing out at the second subtree declaration, on line 12 in the example.

**problem**
This is a problem the structure of the information dictates where we need subtrees, and nested subtrees can not only happen, but may be vital to organizing the docs correctly.

### Reproduce the bug

As quoted in the example above.

### List your environment

Sphinx 5.3.0, sphinx-external-toc 0.3.1.
